### ISSUE TITLE
关于配置问题

### ISSUE THREAD

**Issue by zackzhangkai** [CrazyMouse/cmppSimulateGateway#1]
你好，请教下：如何设置spid passwd这些信息，我在server.properties里没有看到这些参数

**Comment by CrazyMouse** [comment]
呃，抱歉，我都好多好多年不搞电信行业这套东西了，没啥意思，劝你也赶紧跳出这个坑吧

**Comment by CrazyMouse** [comment]
@kaizamm 呃，抱歉，我都好多好多年不搞电信行业这套东西了，没啥意思，劝你也赶紧跳出这个坑吧
